### ISSUE TITLE
Conflict with Consolidated Tabs plugin

### ISSUE THREAD

**Issue by jneilliii** [Kragrathea/OctoPrint-PrettyGCode#54]
@Kragrathea first and foremost, you know I've been a long time user of your plugin and love it. Hands down one of the best UI improvements to OctoPrint. One thing that I've recently noticed is that the fullscreen mode doesn't like to play nice with the Consolidated Tabs plugin, and I assume it has to do with how you are scoping your resize of the tab content. When I merge your tab into the consolidated tab going into fullscreen mode only fills the panel, not the entire page as expected. Here's a screenshot for reference.

![image](https://user-images.githubusercontent.com/5249455/90913734-b17e2080-e3aa-11ea-9c4b-a052e15c4d0a.png)

**Comment by Kragrathea** [comment]
If you can fix the problem with not being able to use the fullscreen link I will try some CSS changes to see if it can behave better.

**Comment by jneilliii** [comment]
I can definitely take a stab at it this weekend. I have a couple of ideas on handling that from my plugin's side.

**Comment by jneilliii** [comment]
That was easier than I though @Kragrathea. I just released version 0.1.2 of Consolidated Tabs that fixes the link not working. When I click it now the pretty gcode fills the containing panel. I believe once the css tweaks are worked out we'll have full functionality/compatibility between the two plugins. Thanks for looking at this and letting me know of that other issue (links not working).

**Comment by Kragrathea** [comment]
Thanks @jneilliii. I'll look into the CSS changes this weekend.

**Comment by Kragrathea** [comment]
Hey @jneilliii I just tried the latest version of Consolidated Tabs and I still have issues with the URL. This form of the URL doesn't take me to the PGC tab in full screen mode. I would guess because PGC is part of a consolidated tab. 
http://192.168.1.5/?fullscreen=1#tab_plugin_prettygcode

My primary use case for PGC is streaming via OBS. So I need a url to go directly into fullscreen mode with the PGC tab focused. 

Maybe what consolidated tabs is trying to do is at odds with the fullscreen mode of PGC is intended for (a pretty but bare minimum full screen UI). Maybe PGC should just not allow fullscreen mode when on a consolidated tab?

**Comment by jneilliii** [comment]
It was working for me...but going into fullscreen view within the panel, not taking over the whole page, which is what the CSS tweaks were needed for. The properties that I used for the jQuery command above if applied to your stylesheet for fullscreen mode I think would resolve it. For reference, this is consolidated tabs PGC in non-fullscreen mode.

![image](https://user-images.githubusercontent.com/5249455/91515357-fe845a00-e8b6-11ea-90fa-6bfacda27a71.png)

and when I click on the fullscreen link, it takes me to that link and loads like this.

![image](https://user-images.githubusercontent.com/5249455/91515414-1fe54600-e8b7-11ea-8a70-e636fdf15bde.png)


running the below commands to tweak the css manually results in true fullscreen view.

```
$('#tab_plugin_prettygcode').css({'position':'fixed','top':'0','left':'0','width':'100%','height':'100%','z-index':'1001'});
$('div.page-container').addClass('pgfullscreen');
```

so my assumption is you could add the css below to the pgfullscreen class maybe?

```
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
z-index: 1001
```

**Comment by jneilliii** [comment]
I did just notice if I do the above it causes the moving of the terminal tab out of view, which is part of positioning issues related to my plugin probably and it's css.

**Comment by jneilliii** [comment]
I can test the css trick I think from my plugin side. I'll let you know how it goes.

**Comment by jneilliii** [comment]
I can confirm, the following css does allow fullscreen mode to work right away. I added it to my css file on my local dev machine and going to the url http://192.168.1.5/?fullscreen=1#tab_plugin_prettygcode worked straight away in the browser. It does re-direct to http://192.168.1.5/?fullscreen=1#tab_plugin_consolidatedtabs but still loads up in fullscreen mode.

```
div.page-container.pgfullscreen #tab_plugin_prettygcode {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: 1001;
}
```

**Comment by jneilliii** [comment]
I could easily just add this to my plugin side and you shouldn't have to change anything on your end.

**Comment by Kragrathea** [comment]
When I run Consoldated Tabs and try to use the URL:
 http://192.168.1.5/?fullscreen=1#tab_plugin_prettygcode 

It redirects to the temperature tab. 
http://192.168.1.5/?fullscreen=1#temp

Probably because that is the first one in my tab order.

**Comment by jneilliii** [comment]
My plugin assumes it comes first using the settings_overlay, but if that's not the case you could have this situation. Use this URL instead.

http://192.168.1.5/?fullscreen=1#tab_plugin_consolidatedtabs instead.

**Comment by Kragrathea** [comment]
For my usage I need to have a URL that consistently links to PGC fullscreen mode. I even have a link in the document tab. To make that work I would need to detect if my window is consolidated and then update the link. And then if someone unconsolidated the tab that URL would stop working. 

Also I tried the CSS you suggested. The z-index entry caused the Status and File windows to display behind the 3d view. If I remove the z-index it sort of works, but the z-index is still messed up and the buttons that toggle the status and file wind up behind the window so they can't be toggled once opened. 

Again I think PGC fullscreen mode is at odds with what consolidated tabs is trying to do. The point was to have just the windows I expect to be open (status, file, dashboard, camera), and have those windows positioned and contained in the 3d view.  Consolidated tabs puts too much of that in the user control and trying to support every use case will be madding.

**Comment by jneilliii** [comment]
Ok, you can close this issue. I'll handle it on my side by overriding your CSS.

**Comment by jneilliii** [comment]
just for your reference, this is what I did...

```
div.page-container.pgfullscreen #tab_plugin_prettygcode {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: 1002;
}

.pgfullscreen #tab_plugin_prettygcode .pgfilestoggle {
	z-index: 1002 !important;
}

.pgfullscreen #tab_plugin_prettygcode .pgstatetoggle {
	z-index: 1002 !important;
}

.pgfullscreen #files_wrapper, .pgfullscreen #state_wrapper {
    position: fixed !important;
    z-index: 1002 !important;
}
```
